project:
  type: website
  output-dir: docs
website:
  title: "matteo blog"
  navbar:
    right:
      - about.qmd
      - icon: facebook
        href: https://www.facebook.com/matteo.pedani
      - icon: twitter
        href: https://twitter.com/matteopedani
      - icon: envelope
        href: mailto:matteo@pedani.it
        aria-label: Email
format:
  html:
    theme: [united, brand,  blog.scss]
    css: styles.css
    toc: true
editor: source
lang: it
max-width: 1900px